/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Meleagor (https://sketchfab.com/Meleagor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mythic-whale-stylized-animated-model-124137f938ec4f5390ddde6dffd7c62e
Title: Mythic Whale - Stylized Animated model
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import scene from '../assets/3d/whale.glb'

const Whale = ({ currentAnimation, ...props}) => {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF(scene)
    const { actions } = useAnimations(animations, group)
  
    // Debug: Check available animation names
    useEffect(() => {
      console.log('Available animations:', animations.map(a => a.name))
    }, [animations])
  
    // Animation control
    useEffect(() => {
      if (actions?.Animation) { 
        actions.Animation.reset().fadeIn(0.5).play()
        
        return () => {
          actions.Animation.fadeOut(0.5)
        }
      }
    }, [actions])
  
    return (
      <group ref={group} {...props} dispose={null}>
        <group name="Sketchfab_Scene">
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            name="Object_72"
            geometry={nodes.Object_72.geometry}
            material={materials.M_Whale}
            skeleton={nodes.Object_72.skeleton}
            position={[0, -0.026, 0.415]}
            rotation={[Math.PI, 0, 0]}
            scale={0.309}
          />
        </group>
      </group>
    )
  }

export default Whale
